----Sample data for table posts
--
--INSERT INTO `posts` (`content`, `description`, `title`) VALUES
--('Spring Boot simplifies Java development with its auto-configuration and starter dependencies.', 'Introduction to Spring Boot framework.', 'Getting Started with Spring Boot'),
--('Java Streams allow for functional-style operations on collections of objects.', 'A guide to Java Stream API basics.', 'Understanding Java Streams'),
--('Docker helps in containerizing applications for consistent deployment.', 'Overview of Docker in modern DevOps.', 'Why Use Docker for Development'),
--('RESTful APIs are a common architectural style for web services.', 'Basics of building RESTful APIs.', 'Creating Your First REST API'),
--
----Sample data for table comments
--
--INSERT INTO `comments` (`body`, `email`, `name`, `post_id`) VALUES
---- Comments for Post ID 1 (Getting Started with Spring Boot)
--('Spring Boot made my project setup so much easier. Excellent article!', 'john.doe@example.com', 'John Doe', 1),
--('I love how Spring Boot minimizes boilerplate code. Great post!', 'jane.smith@example.com', 'Jane Smith', 1),
--('Great guide for beginners! Now I feel more confident with Spring Boot.', 'samuel.brown@example.com', 'Samuel Brown', 1),
--
---- Comments for Post ID 2 (Understanding Java Streams)
--('Java Streams really make working with collections so much cleaner. Great explanation!', 'michael.jones@example.com', 'Michael Jones', 2),
--('Thanks for the deep dive into Streams. I learned a lot about the map function!', 'lucy.white@example.com', 'Lucy White', 2),
--('Very helpful for anyone new to the Java Stream API. Keep it up!', 'andrew.taylor@example.com', 'Andrew Taylor', 2),
--
---- Comments for Post ID 3 (Why Use Docker for Development)
--('Docker has been a game changer for me in terms of deployment. Thanks for this article!', 'katherine.green@example.com', 'Katherine Green', 3),
--('I had no idea how easy it was to use Docker. Your post made it clear and easy to follow.', 'steven.peters@example.com', 'Steven Peters', 3),
--('Docker is essential for scaling applications. This post helped me get started quickly.', 'nancy.james@example.com', 'Nancy James', 3),
--
---- Comments for Post ID 4 (Creating Your First REST API)
--('I was struggling with creating REST APIs in Spring, and this post cleared everything up!', 'paul.martin@example.com', 'Paul Martin', 4),
--('Nice breakdown of REST principles. I will definitely be referring to this guide.', 'lisa.rodgers@example.com', 'Lisa Rodgers', 4),
--('Great post! I will definitely implement REST API in my next project.', 'timothy.foster@example.com', 'Timothy Foster', 4),
