--CREATE DATABASE IF NOT EXISTS myblog;
--
--CREATE TABLE `posts` (
--  `id` bigint NOT NULL AUTO_INCREMENT,
--  `content` varchar(255) NOT NULL,
--  `description` varchar(255) NOT NULL,
--  `title` varchar(255) NOT NULL,
--  PRIMARY KEY (`id`),
--  UNIQUE KEY `UKmchce1gm7f6otpphxd6ixsdps` (`title`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
