--CREATE DATABASE IF NOT EXISTS myblog;
--
--                                     posts Table Structure
--
--CREATE TABLE `posts` (
--  `id` bigint NOT NULL AUTO_INCREMENT,
--  `content` varchar(255) NOT NULL,
--  `description` varchar(255) NOT NULL,
--  `title` varchar(255) NOT NULL,
--  PRIMARY KEY (`id`),
--  UNIQUE KEY `UKmchce1gm7f6otpphxd6ixsdps` (`title`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
--                                     comments Table Structure
--
--CREATE TABLE `comments` (
--  `id` bigint NOT NULL AUTO_INCREMENT,
--  `body` varchar(255) DEFAULT NULL,
--  `email` varchar(255) DEFAULT NULL,
--  `name` varchar(255) DEFAULT NULL,
--  `post_id` bigint NOT NULL,
--  PRIMARY KEY (`id`),
--  KEY `FKh4c7lvsc298whoyd4w9ta25cr` (`post_id`),
--  CONSTRAINT `FKh4c7lvsc298whoyd4w9ta25cr` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
